name: Go Test

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.4

      - name: install Dependency
        run: go mod download
      - name: Test
        run: make test_and_generate_report
      - name: Upload HTML coverage report
        uses: actions/upload-artifact@v4.6.2
        with:
          name: html-coverage
          path: coverReport.html
